io.rsocket.broker.client:
  route-id: 00000000-0000-0000-0000-000000000003
  service-name: verification-service
  tags:
    INSTANCE_NAME: verification-service-1
  brokers:
    - tcp://localhost:8002

logging:
  level:
    io.rsocket.broker.client: DEBUG

---
spring:
  config:
    activate:
      on-profile: verification2

io.rsocket.broker.client:
  route-id: 00000000-0000-0000-0000-000000000002
  tags:
    INSTANCE_NAME: verification-service-2

---
spring:
  config:
    activate:
      on-profile: verification3

io.rsocket.broker.client:
  route-id: 00000000-0000-0000-0000-000000000008
  tags:
    INSTANCE_NAME: verification-service-3